//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachelorWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Learn_BasicEntities : DbContext
    {
        public Learn_BasicEntities()
            : base("name=Learn_BasicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Data> Data { get; set; }
        public virtual DbSet<Elev> Elev { get; set; }
        public virtual DbSet<Gæst> Gæst { get; set; }
        public virtual DbSet<Niveau> Niveau { get; set; }
        public virtual DbSet<Spil> Spil { get; set; }
        public virtual DbSet<SpilNiveauer> SpilNiveauer { get; set; }
        public virtual DbSet<OpgaveSpil> OpgaveSpil { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Test> Test { get; set; }
        public virtual DbSet<Fag> Fag { get; set; }
        public virtual DbSet<Klasse> Klasse { get; set; }
        public virtual DbSet<Lærer> Lærer { get; set; }
        public virtual DbSet<Opgave> Opgave { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
        public virtual DbSet<ipv6_database_firewall_rules> ipv6_database_firewall_rules { get; set; }
        public virtual DbSet<Login> Login { get; set; }
    }
}
