//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BachelorWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpgaveSpil
    {
        public int ID_Opgave { get; set; }
        public int ID_Spil { get; set; }
        public int ID_Niveau { get; set; }
        public Nullable<int> Order { get; set; }
    
        public virtual Niveau Niveau { get; set; }
        public virtual Spil Spil { get; set; }
        public virtual Opgave Opgave { get; set; }
    }
}
